[meta]
  title = "Sinatra Transcription Starter"
  description = "Get started using Deepgram's PreRecorded Transcription with this Sinatra demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "transcription"
  language = "ruby"
  framework = "sinatra"
  tags = ["transcription", "stt", "speech-to-text", "asr", "pre-recorded", "ruby", "sinatra"]

[build]
  command = "bundle install"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "ruby server.rb"
